%%{init: { 'logLevel': 'debug', 'theme': 'base', 'themeVariables': { 'primaryColor': '#ff9800', 'primaryBorderColor': '#ffc107', 'primaryTextColor': '#212121', 'lineColor': '#9e9e9e', 'noteBkgColor': '#e0e0e0' }}}%%
graph LR
   subgraph AllChat["AllChat v3.8"]
       subgraph Application["Application Services"]
           Backend["Backend<br>extender777/allchat-backend"]-->MongoDB
           Frontend["Frontend<br>extender777/allchat-frontend"]-->Backend
           PythonShell["Python Shell<br>python:3.12"]-->Backend
       end

       subgraph Data["Data Services"]
           MongoDB["MongoDB<br>mongo:latest"]
       end

       subgraph Monitoring["Monitoring Services"]
           Prometheus["Prometheus<br>prom/prometheus"]
           NodeExporter["Node Exporter<br>prom/node-exporter"]
           Grafana["Grafana<br>grafana/grafana"]-->Prometheus
           Grafana-->Loki
           Loki["Loki<br>grafana/loki"]
       end
   end

   subgraph Volumes
       MongoData["mongo-data"]
       PrometheusVolume["prometheus"]
       GrafanaVolume["grafana"]
       LokiVolume["loki"]
   end

   MongoDB-->MongoData
   Prometheus-->PrometheusVolume
   Grafana-->GrafanaVolume
   Loki-->LokiVolume

   classDef serviceName fill:#ffc107,stroke:#ff9800,color:#212121;
   class Backend,Frontend,PythonShell,MongoDB,Prometheus,NodeExporter,Grafana,Loki serviceName;