table_manager:
    retention_deletes_enabled: true
    retention_period: 720h

loki:
    limits_config:
        split_queries_by_interval: 2h
        max_query_parallelism: 10
    query_scheduler:
        max_outstanding_requests_per_tenant: 4096
    frontend:
        max_outstanding_per_tenant: 4096
