{
 "title": "Allchat",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status_code)(http_request_duration_seconds_count{job=\"allchat\", method=\"POST\"})",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Time interact, s, 0.95",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "http_request_duration_seconds{quantile=\"0.5\", job=\"allchat\", method=\"POST\", path=\"/interact\", status_code=\"200\", instance=\"172.17.0.1:6000\"}",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time( {container=\"/allchat_backend_1\"} |= `interact`[1h])"
    }
   ]
  },
  {
   "title": "Payments",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(count_over_time({container=\"/allchat_backend_1\"} |= `✅ Success:` [5m]))"
    }
   ]
  },
  {
   "title": "Time run, s, 0.95",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 9 },
   "targets": [
    {
     "expr": "http_request_duration_seconds{quantile=\"0.95\", job=\"allchat\", method=\"POST\", path=\"/run\", status_code!=\"499\"}",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "/run",
   "type": "logs",
   "gridPos": { "h": 5, "w": 9, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "{project=\"allchat\"} |= `/run` "
    }
   ]
  },
  {
   "title": "Errors",
   "type": "logs",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{project=\"allchat\"} |= `Error`"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 24 },
   "targets": [
    { "expr": "{project=`allchat`}" }
   ]
  },
  {
   "title": "/interact",
   "type": "logs",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "{project=\"allchat\"} |= `/interact` "
    }
   ]
  },
  {
   "title": "/register",
   "type": "logs",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "{project=\"allchat\"} |= `/register` "
    }
   ]
  },
  {
   "title": "/login",
   "type": "logs",
   "gridPos": { "h": 9, "w": 10, "x": 13, "y": 48 },
   "targets": [
    {
     "expr": "{project=\"allchat\"} |= `/login` "
    }
   ]
  }
 ]
}