{
 "title": "Nginx",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "404",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"nginx\", level=~\"info\"} | pattern `<_> - - <_> \"<method> <_> <_>\" <status> <_> <_> \"<_>\" <_>` | status = `404`"
    }
   ]
  },
  {
   "title": "500",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"nginx\", level=~\"info\"} | pattern `<_> - - <_> \"<method> <_> <_>\" <status> <_> <_> \"<_>\" <_>` | __error__=`` | status >= 500"
    }
   ]
  },
  {
   "title": "Access",
   "type": "logs",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"nginx\", level=~\"info\"} | pattern `<_> - - <_> \"<method> <_> <_>\" <status> <_> <_> \"<_>\" <_>`"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "logs",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"nginx\", level=~\"error\"}"
    }
   ]
  },
  {
   "title": "Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "count_over_time({job=\"nginx\"} [5m])"
    }
   ]
  },
  {
   "title": "Statuses",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (count_over_time({job=`nginx`, level=\"info\"}  | pattern `<_> - - <_> \"<method> <_> <_>\" <status> <_> <_> \"<_>\" <_>`   [$__range]))"
    }
   ]
  },
  {
   "title": "Method",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method) (count_over_time({job=`nginx`, level=\"info\"}  | pattern `<_> - - <_> \"<method> <_> <_>\" <status> <_> <_> \"<_>\" <_>`  |__error__= `` [$__range]))"
    }
   ]
  }
 ]
}